#!/bin/bash
#####################################################################################
#####################################################################################
########################## Belgenet YÜKLEME ########################################
#####################################################################################
#####################################################################################
#####################################################################################
FILE="/usr/local/signNativeOsService/signNativeOsService.jar"
HASH="2ebe2c51e52e52c495019c5f041d6ad324208988"
SSH_COMMAND=$(echo "$HASH $FILE" | sha1sum -c | grep Tamam | wc -l)

hash=$(sha1sum $FILE |cut -d ' ' -f 1)
if [ "$SSH_COMMAND" -eq "1" ]
	then
		echo "OK. Belgenet versiyon 1.0.49. $hash "
		exit 0
	fi

cd /tmp/afad-belgenet
unzip signNativeOsService_Linux_1.0.49.zip
cd signNativeOsService/bin/systemctl/
chmod 777 install.sh
systemctl stop turksat-imza
bash install.sh
cd /tmp
rm -rf /tmp/afad-belgenet
FILE="/usr/local/signNativeOsService/signNativeOsService.jar"
HASH="2ebe2c51e52e52c495019c5f041d6ad324208988"
SSH_COMMAND=$(echo "$HASH $FILE" | sha1sum -c | grep Tamam | wc -l)

hash=$(sha1sum $FILE |cut -d ' ' -f 1)
if [ "$SSH_COMMAND" -eq "1" ]
	then
		echo "OK. Belgenet versiyon 1.0.49. $hash "
	else 
	echo "Warning.  Kurulum basarisiz. "
	fi
